### ISSUE TITLE
Server always sleeping

### ISSUE THREAD

**Issue by XonaProto** [haveachin/infrared#10]
Hi,
sadly I can't use the proxy because I always get this error message when trying to connect to the minecraft server:
Could not determine if the container is running error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" connection=xx.x.xx.xxx:51925 destinationAddress=:25566 domainName=xxx.ddns.net event=Error gate=:25565
I made the container using the docker-compose file from this git repo.

**Comment by Schmoaaaaah** [comment]
I added this and it solfed the issue.
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

But know it always says that the server was sleeping when trying to connect.

**Comment by XonaProto** [comment]
I already tried this but it sadly didn't fix the issue.

**Comment by MB175** [comment]
I will take a look at your issue soon stay tuned

**Comment by MB175** [comment]
By the time please provide your docker version as well as your system version

**Comment by XonaProto** [comment]
I just pulled the newest infared proxy version and added - "/var/run/docker.sock:/var/run/docker.sock" to my docker-compose file. The error is actually gone now. Now I have the same issue as Schmoaaaaah. When connecting to the server it always says that it is sleeping.

Here is my docker version: Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Here is my docker-compose version:
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

I am using Ubuntu Server 20.04 with all the latest updates.

**Comment by MB175** [comment]
Okay, can you please provide us your server configs as well as your docker compose file

**Comment by MB175** [comment]
in addition take a look at this issue #11 
Make sure you set your config as i mentioned here [Issue](https://github.com/haveachin/infrared/issues/11#issuecomment-726287161)

**Comment by XonaProto** [comment]
Thank you. Everything is working now! :)
