### ISSUE TITLE
Connection refused, infinite restart loop

### ISSUE THREAD

**Issue by felix920506** [haveachin/infrared#101]
followed the instructions
couldn't connect with message connection refused
had a look and the container seems to be stuck in an infinite restart loop
log as below
![image](https://user-images.githubusercontent.com/25688628/131396929-1fc31a97-b898-40c7-8946-10c3945782df.png)

**Comment by haveachin** [comment]
On what architecture are you running the container (amd64, arm64, ...)?

**Comment by felix920506** [comment]
I'm running it on arm64 (raspberry pi 4 B 4GB) with ubuntu 20.04

**Comment by haveachin** [comment]
We only have a prebuild docker container for amd64 at the moment, so you have to build it yourself. But don't worry it is very easy:
```
git clone https://github.com/haveachin/infrared
```
Then do `cd infrared` and `nano Dockerfile`. Here you just have to change the `GOARCH` in line 6 to `GOARCH=arm64`.
After that just build the image
```
docker build --no-cache -t haveachin/infrared:latest .
```
Now you should be able to deploy it with something like this
```
docker run -d --name infrared --restart=unless-stopped -it -v /usr/local/infrared/configs/:/configs -p 25565:25565/tcp --expose 25565 haveachin/infrared:latest
```
Put your Infrared proxy configs in this folder `/usr/local/infrared/configs`.

**Comment by felix920506** [comment]
Thanks, I'll try that out later. I'm currently trying infrared out another machine running x86.

**Comment by felix920506** [comment]
It works now, thanks. Maybe consider adding this into the documentation with a table of which architecture should use what `GOARCH` setting?
by the way what should I put there if I want to run this on a 32-bit arm system?

**Comment by haveachin** [comment]
Just `GOARCH=arm` I think

**Comment by Catospye** [comment]
arm is pain in ass
