### ISSUE TITLE
error invalid character 'b' looking for beginning of value

### ISSUE THREAD

**Issue by felix920506** [haveachin/infrared#102]
**Describe the bug**
Won't load config, spits out the error "error invalid character 'b' looking for beginning of value"

**To Reproduce**
What OS are you using?
Ubuntu Server 20.04.3
What version of Infrared are you using?
V1.1.1-beta
What do your Infrared proxy config(s) look like?
{
  "domainName" : "example.com",
  "proxyTo" : "example.com:25566",
  "proxyProtocol" : true
}
How do you trigger the bug/issue?
create the config file using nano and it sometimes breaks

**Expected behavior**
I expected the config file to load

**Screenshots** (Optional)
A copy of your logs would be nice, but please be sure to censor any information that you don't want to be public.

**Additional context** (Optional)
Add any other context of the problem here.

**Comment by haveachin** [comment]
Infrared is trying to automatically discover new configs. Your text editor (probably nano) is creating a temporary file while you are editing. So this is not an bug, it's a feature! :)

**Comment by daisyUniverse** [comment]
Having a similar issue, using micro to create the file, looking and verifying there are no other files in the /configs/ directory, and then it's giving the same error as this one - Almost definitely user error but I'm a bit stuck here.. 

EDIT: Going to try the docker image next, if I had to guess I'd say maybe there's some kinda library problem causing the yaml parser to bork in some way

**Comment by haveachin** [comment]
Maybe there is an indentation error or a weird unicode character in your config. I'd recommend validating the config. Sometimes copy and pasting it into a different code editor also helps idk why tho

**Comment by daisyUniverse** [comment]
I copied the config file to a docker instance and it seemed to work fine there - can't really explain it, but I guess the problems been worked around in case anyone was looking for a way to get around this

> Maybe there is an indentation error or a weird unicode character in your config. I'd recommend validating the config. Sometimes copy and pasting it into a different code editor also helps idk why tho

I was working off a direct copy-paste of the example config yaml without any changes so I don't suspect that this is it 

PS: Once it's running this works fantastically, thank you for saving me from having to figure out how to proxy UDP traffic with Nginx or Caddy 14
