### ISSUE TITLE
Unable to set server icon (iconPath)

### ISSUE THREAD

**Issue by tomassystems** [haveachin/infrared#103]
When I specify a path to a server icon, I simply get "error: open ./icons/cozy.png: no such file or directory".

This is what my directory setup looks like:

![image](https://user-images.githubusercontent.com/65788180/133879708-1ed2175c-aead-486f-871b-9f7b75905bb2.png)

Within the `iconPath` field, I enter `./icons/cozy.png`, I've also tried `../icons/cozy.png` and moving the actual `icons` folder into the `configs` folder.

**Comment by realDragonium** [comment]
Try using the absolute path of the icon

**Comment by tomassystems** [comment]
Same issue, unfortunately. Still get the open error.

**Comment by haveachin** [comment]
Reopen if needed

**Comment by MyMeepSQL** [comment]
I've encountered the same problem. We know that the default folder given in the repo to deploy the container is `/usr/local/infrared/configs/` for the `/configs` folder inside the container (which can be modified, of course, but I've left it as is).

So in my configuration file, I first tried to do as you do (with the absolute path but from the computer, not the container). Then I put `/configs/server-icon.png` (the absulute path in the container) and it seems to find the file but with this error:
```
2023/08/04 16:03:08 Failed loading proxy configs from ./configs; error: invalid character '\u0089' looking for beginning of value
```

@haveachin do you have any idea about the `invalid character '\u0089' looking for beginning of value` error ?
