### ISSUE TITLE
Protocol as external lib

### ISSUE THREAD

**Issue by dada513** [haveachin/infrared#110]
**Is your feature request related to a problem? Please describe.**
The protocol functions of infrared would be very useful for other golang projects, IMO

**Describe the solution you'd like**
Publish protocol as separate go package with docs

**Comment by lhridder** [comment]
Do you mean the proxyProtocol and realIp integrations?

**Comment by dada513** [comment]
> Do you mean the proxyProtocol and realIp integrations?
No, I mean the minecraft protocol in general. Would be useful in other Go projects

**Comment by realDragonium** [comment]
Infrared only has and uses the login parts of the protocol, it doesn't have any code related to any other packets

**Comment by haveachin** [comment]
Well there is also this project I started a while ago https://github.com/specspace/plasma
