### ISSUE TITLE
Can't build from source locally

### ISSUE THREAD

**Issue by JohnEridium** [haveachin/infrared#123]
**Describe the bug**
Building from source is impossible (in a way)

**To Reproduce**
I was trying to get the Prometheus node exporter functionality earlier, so I forked this repository and implemented the changes from pull request #120 in my fork.
I also edited all github links in all files to point to the exact same location in my fork on GitHub. But the build process failed with an error saying that something along the lines of "no module provides package github.com/JohnEridium/infrared/api" or something similar. 
Neither a local docker build, nor a remote docker build (as seen in the readme under "Deploy" and "Update") worked and only worked if the original GitHub URL/Path was given.

Link to my fork:
https://github.com/JohnEridium/infrared.git

**Expected behavior**
I expected that a local build would be possible if all URLs/addresses/links were changed and the code was available locally. I'm just curious as of why this did not work.

The attached txt file shows the exact process I have attempted.
[infrared-error.txt](https://github.com/haveachin/infrared/files/8010603/infrared-error.txt)

**Comment by realDragonium** [comment]
While, this is not how go modules work, the easiest would be to clone the repo and build it without modifying anything
