### ISSUE TITLE
Add RealIP-Passthrough support (if not already implemented)

### ISSUE THREAD

**Issue by KaktusXY** [haveachin/infrared#132]
**Is your feature request related to a problem? Please describe.**
I really like selfhosting servers from home so I used TCPShield (primarily to hide my ip), but I have multiple mc servers so I have to forward multiple ports.

**Describe the solution you'd like**
It would be awesome if you could use TCPShield(or other infrared instance) infront of infrared and use RealIP to passthrough the IP from TCPShield to infrared to the server.

![image](https://user-images.githubusercontent.com/58702689/158466795-42f17de4-db61-4a27-aafc-0eaacb6e450b.png)

**Comment by haveachin** [comment]
This should already work. Did you test it?

**Comment by KaktusXY** [comment]
No, because RealIP is currently not working, I tried it and see #71

**Comment by haveachin** [comment]
But pass thru should work. Do **not** set `"realIp": true` in the config since this will override the TCPShield handshake packet modification. Otherwise it should work.

**Comment by KaktusXY** [comment]
Just tried it, it works. Thanks for the help. Maybe add some information about this in to the new docs for v2.0

**Comment by KaktusXY** [comment]
Is it possible to implement, that infrared is able to "intercept" the RealIP packet and shows the real player ip in the logs for e.g. maybey in the future for some metrics, api, etc..?

**Comment by KaktusXY** [comment]
Is it possible to implement, that infrared is able to "intercept" the RealIP packet and shows the real player ip in the logs for e.g. maybey in the future for some metrics, api, etc..?

**Comment by haveachin** [comment]
Is already planned for 2.0
