### ISSUE TITLE
Left Motd

### ISSUE THREAD

**Issue by Pui142** [haveachin/infrared#135]
**Describe the bug**

When i use infrared the Left Motd is missing
![image](https://user-images.githubusercontent.com/103855220/166812982-0921db98-9f3d-4081-b3b6-9141e2d4d401.png)

**Comment by haveachin** [comment]
Should work if you make the version name long enough to clip to the other side. You need to make something like 71 characters (most of the spaces) to achieve that. I would look something like that: 
```
[1.8.x - 1.19.2]                                                               Infrared
|<------------>|<-------------------------------------------------------------------->|
  Your string                  71 characters (most of them spaces)         
```
