### ISSUE TITLE
how to use bed rock version

### ISSUE THREAD

**Issue by MicotoTisaki** [haveachin/infrared#137]
We are currently using GNU screen to dynamically build multiple bedrock servers. We would like to use infrared to reverse-proxy each subdomain.
I was able to create a similar configuration using the java version, but I was wondering if it is possible to add POST or launch docker by itself in bedrock. And if so, what docker file or docker-compose.yml should I use?

**Comment by MicotoTisaki** [comment]
Thanks for the reply. I found in a past issue that there is a test code in the rewrite branch, but I see that it is in the process of being implemented properly.
I am looking forward to the implementation in the master branch as infrared is very easy to use.

**Comment by haveachin** [comment]
Bedrock will no longer be supported by Infrared. Sorry for any inconvenience.
