### ISSUE TITLE
Can no build on CentOS 8

### ISSUE THREAD

**Issue by alexgg43** [haveachin/infrared#14]
Hi guys i can not run the docker file.

Error at the line 6:

Step 6/14 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main .
 ---> Running in be20dbc8ce2c
go: github.com/Microsoft/go-winio@v0.4.14: Get "https://proxy.golang.org/github.com/%21microsoft/go-winio/@v/v0.4.14.mod": dial tcp: lookup proxy.golang.org on 1.1.1.1:53: read udp 172.17.0.2:41831->1.1.1.1:53: read: no route to host
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main .' returned a non-zero code: 1

**Comment by haveachin** [comment]
Please check if your docker environment has access to the internet. Otherwise you could just pull the prebuild container from docker hub with `docker pull haveachin/infrared:latest`.

**Comment by frantisekhanzlikbl** [comment]
Did you get this sorted out? I am currently facing the same problem (also on CentOS 8).

**Comment by MB175** [comment]
@frantisekhanzlikbl we got no response on this so far. To sort things out and make sure you have no further configuration issues you could just pull the prebuild container from docker hub with docker pull haveachin/infrared:latest and try running from there.

If you really want to build the image yourself please provide further logs.

**Comment by frantisekhanzlikbl** [comment]
I have avoided this problem by switching to Ubuntu. CentOS has a too old kernel.

**Comment by MB175** [comment]
Interesting, older kernel versions shouldn't be an issue. Nice too know I will take an eye on that and find out what exactly causes such behavior.
