### ISSUE TITLE
When using BungeeCord you cannot join the server.

### ISSUE THREAD

**Issue by AlignedCookie88** [haveachin/infrared#153]
I have been trying to set up this proxy to work with BungeeCord. I have set prevent_proxy_connections to false in the BungeeCord config and always get this warning:

`[WARNING] InitialHandler - bad packet ID, are mods in use!? Packet LOGIN:TO_SERVER/0 (LoginRequest) larger than expected, extra bytes: 819`

**Comment by haveachin** [comment]
Looks like a proxy protocol error, but I'm not sure.

**Comment by samuxita** [comment]
i'm using the same system and its working

**Comment by AlignedCookie88** [comment]
yes it just magically started working a while ago and I forgot about this thread sorry

it might have been something about the bungeecord version
