### ISSUE TITLE
Seems like an error with config refresh

### ISSUE THREAD

**Issue by tiboxoff** [haveachin/infrared#158]
So its really easy to reproduce default java config file

java:
  gateways:
    default:
      listeners:
        default:
          bind: :25566
  servers:
    default:
      gateways:
        - default
      domains:
        - "*"
      address: 192.168.10.104:25565
      overrideStatus:
        versionName: Infrared
        maxPlayerCount: 777777777
        playerCount: 2

so versionName is gonna be 'Infrared' right ? yes it is

but now remove the whole overrideStatus section is the versionName '1.12.2' (server version) ? no its Infrared

**Comment by haveachin** [comment]
Could you please post screenshots of what you are referring to? I have a feeling that you might be looking at the dialTimeoutStatus by accident.

**Comment by tiboxoff** [comment]
ok so if i start the server with that conf
java:
gateways:
default:
listeners:
default:
bind: :25566
servers:
default:
gateways:
- default
domains:
- "*"
address: 192.168.10.104:25565

![image](https://user-images.githubusercontent.com/39035551/198552862-4737fd53-6114-448c-979b-4fbb23dcc0fd.png)

then i edit it to
java:
gateways:
default:
listeners:
default:
bind: :25566
servers:
default:
gateways:
- default
domains:
- "*"
address: 192.168.10.104:25565
overrideStatus:
versionName: Infrared
maxPlayerCount: 777777777
playerCount: 2

![image](https://user-images.githubusercontent.com/39035551/198553032-452ba465-5f5f-4b94-956f-e0fc13e81d13.png)

then i go back to 
java:
gateways:
default:
listeners:
default:
bind: :25566
servers:
default:
gateways:
- default
domains:
- "*"
address: 192.168.10.104:25565

![image](https://user-images.githubusercontent.com/39035551/198553108-566158ad-1d54-4c0c-9fc4-cc9147c47a80.png)

**Comment by haveachin** [comment]
I think I found the issue. It has something to do with the library I use for merging the config maps. I have absolutely no clue why it behaves that way, but I seems like it caches the pointer to that   string. I will have to investigate that further and probably end up opening an issue or writing a map merge function myself.
