### ISSUE TITLE
Infrared cannot ping or pass connection to server

### ISSUE THREAD

**Issue by SomeAspy** [haveachin/infrared#161]
**Describe the bug**
It seems that Infrared cannot see the server.

**To Reproduce**
Ubuntu 22.04.1
Latest Docker image for 11/17/22
`{
  "domainName": "{redacted}.aspy.dev",
  "proxyTo": "127.0.0.1:25566"
}`
This issue is triggered when Infrared is started

**Expected behavior**
Infrared should be able to ping and pass connections to the server

**Screenshots** (Optional)
![AMB-DESKTOP521617November2022](https://user-images.githubusercontent.com/33640860/202567681-bcda1581-d403-444c-b8e9-978bd9f14669.png)

**Comment by tiboxoff** [comment]
why do you hide the ip before 25566

**Comment by SomeAspy** [comment]
@tiboxoff It logged my VPS IP, not 127.0.0.1

**Comment by tiboxoff** [comment]
strange

**Comment by haveachin** [comment]
Feel free to reopen if you are still having issues or join our discord and get support there
