### ISSUE TITLE
Can you add  Whitelist Mechanism ？ And  Create/Read/Update/Delete Configs

### ISSUE THREAD

**Issue by cniu6** [haveachin/infrared#165]
Can you add  Whitelist Mechanism ？ And  Create/Read/Update/Delete Configs

in Bedrock minecraft.♛

**Comment by haveachin** [comment]
Whitelist for Bedrock, maybe and CRUD operations for configs were added with v2.0.0-alpha.13

**Comment by haveachin** [comment]
Bedrock will no longer be supported by Infrared. A whitelist should probably be implemented by the backend server since Infrared does not do any session validation.
