### ISSUE TITLE
no connection to docker server

### ISSUE THREAD

**Issue by DerSteph** [haveachin/infrared#18]
hello,
i recently installed infrared on a testsystem with two minecraft server in docker. However there is no connection between them. Everytime when i try to connect to a subdomain i get the error "Hey username! The server was sleeping but it is starting now."

![grafik](https://user-images.githubusercontent.com/37001354/104850156-c0cbb080-58ed-11eb-815c-70637a4228f9.png)

**Comment by MB175** [comment]
Hello @DerSteph can you provide us with your docker-compose file, as well as one of your proxy config Files.
In Addition please make sure the Containers you want to connect to are set to the same docker network.

**Comment by DerSteph** [comment]
docker-compose.yml for infrared

`version: "3.3"

services:
  infrared:
    build: https://github.com/haveachin/infrared.git
    container_name: infrared
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /usr/local/infrared/configs/:/configs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "25565:25565"
    expose:
      - "25565"
    networks:
      - minecraft
    environment:
      - INFRARED_DEBUG=true

networks:
  minecraft:
    external: true
`

docker-compose.yml for mc server
`version: "3.3"

services:
  papermc:
    image: phyremaster/papermc
    container_name: papermc
    restart: unless-stopped
    volumes:
      - /usr/local/papermc/:/papermc
    networks:
      - minecraft
  mc:
    image: itzg/minecraft-server
    container_name: mc
    restart: unless-stopped
    networks:
      - minecraft
    environment:
      - EULA=true

networks:
  minecraft:
    external: true
`

mc.locald.yml configfile
`DomainName: "mc.locald"
ProxyTo: ":25565"
ProxyProtocol: true
Docker:
  ContainerName: "papermc"
Server:
  Version: "1.16.5"
`

mc2.locald.yml configfile
`DomainName: "mc2.locald"
ProxyTo: ":25565"
ProxyProtocol: true
Docker:
  ContainerName: "mc"
`

my testsystem runs on a vmware virtual machine and i set the subdomains via my /etc/hosts file under Windows

**Comment by MB175** [comment]
Seems right but did you made sure that your Minecraft containers are in the same Docker network as your infrared container ?

**Comment by DerSteph** [comment]
networks:
- minecraft

i set both in the network minecraft. i created the network externally.

**Comment by haveachin** [comment]
I think you are missing your container names in your infrared configs. Try adding them to the ProxyTo field:  

mc.locald.yml
`ProxyTo: "papermc:25565"`

mc2.locald.yml
`ProxyTo: "mc:25565"`

If you're still experiencing problems with your configuration then feel free to hop in our [Discord server](https://discord.gg/yjzJVhvN) (expires in 24h)

**Comment by MB175** [comment]
Please make sure Proxy Protocol isnt enabled, except for servers which are configured to handel custom proxy protocol packages
