### ISSUE TITLE
no matter what i do i cant seem to get it to connecet

### ISSUE THREAD

**Issue by Deadshot222224** [haveachin/infrared#187]
**im not 100% sure if this is a bug but the bug is when you load the config by starting the proxy it works fine people can connect to the proxy my minecraft server is online it cant seem to connect to the minecraft server i can see in the log people are connecting to the proxy server basically gives the output of asking wether or not the server is up or not it does this because when it pings my minecraft server the server doesnt ping back so im guessing it denies the connection based on that?**

**To Reproduce**
windows 11 with infrared running on wsl2 and the minecraft server running on mcss the server managament software for windows?
What version of Infrared are you using? haveachin/infrared:latest
IN USE
66791fa577ab

{
  "domainName": "sub.domain.org",
  "listenTo": ":<alt-port>",
  "proxyTo": "<public-ip><port>"
}?
How do you trigger the bug/issue? i just loaded up the config and had a frriend join

**Expected behavior**
i expected it to be able to connect to my server and redirect traffic

**Screenshots** (Optional)
A copy of your logs would be nice, but please be sure to censor any information that you don't want to be public.

**Additional context** (Optional)
some other context im not that experienced in networking like this ive mainly been having chat gpt teach me bit by bit because when i try going into the syntax of some of the intense coding this can go into my brain does not want to co-operate T_T

**Comment by haveachin** [comment]
This version of Infrared will no longer be supported. If you have any issue with the latest release please let me know.
