### ISSUE TITLE
Bug when connect with Forge

### ISSUE THREAD

**Issue by kotori2** [haveachin/infrared#2]
client will send the server address like `mc.example.com.\x00FML\x00`, which is not configureable in config file.

**Comment by Doctor-Mo** [comment]
Thats an pretty easy fix just simply add the additional chars provided by your client to the DomainName field provided in the config.

Example:
``DomainName: "mc.example.com.\x00FML\x00"``

**Comment by haveachin** [comment]
I'm looking into it. Please use this as a workaround in the meantime.

> Thats an pretty easy fix just simply add the additional chars provided by your client to the DomainName field provided in the config.
> 
> Example:
> `DomainName: "mc.example.com.\x00FML\x00"`

**Comment by haveachin** [comment]
I pushed a fix. Should be working now.
