### ISSUE TITLE
Build files for v2.0.0-alpha.15

### ISSUE THREAD

**Issue by FerroEduardo** [haveachin/infrared#200]
Could you provide the build/compiled files for [v2.0.0-alpha.15](https://github.com/haveachin/infrared/releases/tag/v2.0.0-alpha.15)? Although the tag is created, there is no asset ready to use

**Comment by haveachin** [comment]
Sorry, there where issues with the pipeline. I'll look into it

**Comment by haveachin** [comment]
I've decided to skip to release this version. All the time I'm able to allocate for Infrared will be directed towards the new rewrite and future releases. v2.0.0-alpha.15 was and will be the last checkpoint of the failed rewrite attempt.
