### ISSUE TITLE
TCP connection forwarder.

### ISSUE THREAD

**Issue by Mitch0S** [haveachin/infrared#28]
Hello :)

I'm currently using this as DDoS protection for a few servers, my only problem is that there is a bandwidth cap of 750GB per proxy. 

I currently have multiple A records as an attempt to spread the load between my proxies, but is quite inefficient as one more usage than the other.

If it were possible to have a TCP connection forwarder that can send the hostname in a header to infrared, that would be amazing! If that is working, I could turn it into a load balancer :)

Thanks,

Mitch, AusGuard.net

**Comment by haveachin** [comment]
Hey Mitch

At the moment I'm refactoring Infrared to support faster development cycles for future updates and features. FYI there will be **breaking changes** to the proxy configs as Infrared has it's **first official release**. 

I'm not sure what you mean by sending a hostname in a header, but you could just send a Minecraft [handshake packet](https://wiki.vg/Protocol#Handshaking) which contains the hostname followed by a [login sequence](https://wiki.vg/Protocol#Login). I could also just add a load balancing feature as requested by #26.

Best,
Haveachin

**Comment by Mitch0S** [comment]
Sorry for the late reply, 

What I mean, is when a player joins the forwarder/load balancer, it forwards them to one of multiple proxies we have. When the player is send the the proxy, would it be able to see the hostname that the player connected through? Or would it be the IP of the box hosting the forwarder?

Thanks,

Mitch, AusGuard.net

**Comment by haveachin** [comment]
No worries.

TCP is not aware of domains. You can only see it's source and destination address in the TCP protocol header. However the Minecraft protocol sends the literal address that the player has entered in his server address box on the Minecraft client.
E.g. "eXAMPle.com" will be transmitted as "eXAMPle.com"

On the other hand the HAProxy protocol supports an origin address field. That enables you to do IP bans, etc. without banning the IP address of you proxies. See #8.

If you want to know if you can chain infrared instances then the answer is yes, you can do that.

Best,
Haveachin

**Comment by Mitch0S** [comment]
Ahh all good.

So if we had a relay server, that just forwards the player to a proxy, it would still be able to detect the host that the client connected through originally and proxy accordingly?

Thanks,

Mitch

**Comment by haveachin** [comment]
Yes, that should work.

Best,
Haveachin
