### ISSUE TITLE
Spamming console with silly message given context

### ISSUE THREAD

**Issue by endigma** [haveachin/infrared#36]
The application spams the console with "x did not respond to ping; is the target offline?" when it should know whether or not the target is offline because these servers are managed by infrared's docker functionality?

Useless spam in the logs.

**Comment by endigma** [comment]
on a related note:

![image](https://user-images.githubusercontent.com/34945114/109863736-6174f600-7c38-11eb-868c-6caa2c79350d.png)

the program doesn't seem to persistently keep track of container timeouts, so it attempts stopping it several times over as a result of multiple timeouts being created

**Comment by haveachin** [comment]
> The application spams the console with "x did not respond to ping; is the target offline?" when it should know whether or not the target is offline because these servers are managed by infrared's docker functionality?
> 
> Useless spam in the logs.

I think that is debatable, but I agree that there is a lot of spam.
Would you like a feature flag for debug logs?

**Comment by haveachin** [comment]
> on a related note:
> 
> ![image](https://user-images.githubusercontent.com/34945114/109863736-6174f600-7c38-11eb-868c-6caa2c79350d.png)
> 
> the program doesn't seem to persistently keep track of container timeouts, so it attempts stopping it several times over as a result of multiple timeouts being created

I'm sorry, I'm not able to replicate that.

**Comment by haveachin** [comment]
Feel free to reopen with more info on the issue
