### ISSUE TITLE
IP forwarding & Callback

### ISSUE THREAD

**Issue by nathangimblett17** [haveachin/infrared#42]
Hey,

I recently installed Infrared by using the docker install link in the README.md, and I've been having issues getting the HAProxy IP-forwarding to work & Callbacks.

The issue with the IP Forwarding is when I enable the proxy_protocol in Bungeecord and proxy in Infrared, every time I join I instantly get kicked with no error and just a black kick message. The bungeecord also fails to see me connecting.

The issue with Callback is that when I use the example off of the full config example and enter my own URL, it never receives any POST requests, even when added into the config as shown in the example.

Have you got any idea why this doesn't work?

Thanks,
Nathan

**Comment by NeadApTar** [comment]
Same problem. In motd "Pinging..." or "Can't connect to server". Without `"proxyProtocol": true` in Infrared and `proxy_protocol: true` in WaterFall everything works fine. Installed haproxy and everything works well through it.
Proxy Log:
![image](https://user-images.githubusercontent.com/34768994/113302514-ce97ac00-9308-11eb-9f38-36077f447c81.png)

**Comment by nathangimblett17** [comment]
Interesting, I’m confused why Bungeecord won’t just allow it. I might try have a friend implement a similar method to TCPShield for IP Forwarding as theirs constantly works really well. However, I’m still confused why I can’t get Callback to work. It just looks like nothing ever gets sent through from Infrared.

**Comment by MB175** [comment]
Could you describe your setup step by step as well as the connections between the containers ?

**Comment by nathangimblett17** [comment]
I'm only using 1x Container for Infrared and the web-server listening to the callback & the MC server its being connected to are all external elsewhere.

**Comment by MB175** [comment]
Well sounds like everything should work just fine. If you want you can join our discord and we can take a closer look and talk about it.

[Discord Join!](https://discord.gg/QH42PUhqBz)
