### ISSUE TITLE
HAProxy Protocol support for incoming connections

### ISSUE THREAD

**Issue by danieldimbarre** [haveachin/infrared#55]
Hello, 
I would like to know if the infrared has support for the ovh load balancer that defines an output ip different from the client's real ip

**Comment by haveachin** [comment]
Hey, I'm not sure what you mean by that, but you can proxy the client's real IP through Infrared easily.
There are two officially supported methods yet. The first one would be using the HA Proxy protocol. This will send a proxy header containing the clients real IP to your BungeeCord (you have to enable proxy-protocol in the config there).
Another way would be using RealIP. That would require your server or proxy to install the [RealIP Plugin](https://github.com/TCPShield/RealIP) by TCPShield and then add the IP of the server where Infrared is running to the IP list in the plugin config.

**Comment by nathangimblett17** [comment]
> Hello,
> I would like to know if the infrared has support for the ovh load balancer that defines an output ip different from the client's real ip

If you’re going OVH Balancer -> Infrared you will need software which can convert the IP they add into the request using HAProxy. Infrared can then forward this how Haveachin said.

If you’re going Infrared -> OVH Balancer I’m fairly sure you will need the RealIP protocol or Infrared won’t be able to forward the request properly due to the OVH Balancer not picking up the clients real IP from Infrared.

**Comment by danieldimbarre** [comment]
> > Hello,
> > I would like to know if the infrared has support for the ovh load balancer that defines an output ip different from the client's real ip
> 
> If you’re going OVH Balancer -> Infrared you will need software which can convert the IP they add into the request using HAProxy. Infrared can then forward this how Haveachin said.
> 
> If you’re going Infrared -> OVH Balancer I’m fairly sure you will need the RealIP protocol or Infrared won’t be able to forward the request properly due to the OVH Balancer not picking up the clients real IP from Infrared.

you know one software to convert the ip in OVH Balancer -> Infrared?

**Comment by nathangimblett17** [comment]
> > > Hello,
> > > I would like to know if the infrared has support for the ovh load balancer that defines an output ip different from the client's real ip
> > 
> > 
> > If you’re going OVH Balancer -> Infrared you will need software which can convert the IP they add into the request using HAProxy. Infrared can then forward this how Haveachin said.
> > If you’re going Infrared -> OVH Balancer I’m fairly sure you will need the RealIP protocol or Infrared won’t be able to forward the request properly due to the OVH Balancer not picking up the clients real IP from Infrared.
> 
> you know one software to convert the ip in OVH Balancer -> Infrared?

I’m fairly sure you can do it with HAProxy as that’s what OVH are using to proxy through their Load Balancer.

**Comment by haveachin** [comment]
[I found out what OVH uses for their TCP proxies](https://docs.ovh.com/gb/en/load-balancer/loadbalancer-introduction/). If you want a setup that looks like this:

[Minecraft Client] -> [OVH Load Balancer] -> [Infrared] -> [Minecraft Server]

then I will have to add HAProxy Protocol support for incoming packages. @danieldimbarre is this what you need?

**Comment by danieldimbarre** [comment]
> [I found out what OVH uses for their TCP proxies](https://docs.ovh.com/gb/en/load-balancer/loadbalancer-introduction/). If you want a setup that looks like this:
> 
> [Minecraft Client] -> [OVH Load Balancer] -> [Infrared] -> [Minecraft Server]
> 
> then I will have to add HAProxy Protocol support for incoming packages. @danieldimbarre is this what you need?

yes thx

**Comment by danieldimbarre** [comment]
![image](https://user-images.githubusercontent.com/49664655/114632042-2bde1680-9c94-11eb-8f50-8d4f925003ce.png)
New error .-.

**Comment by haveachin** [comment]
The feature is not live yet. Code is under review right now. I will let you know when it's live.
