### ISSUE TITLE
Prometheus Exporter

### ISSUE THREAD

**Issue by NeadApTar** [haveachin/infrared#63]
I launched Infrared on 5 servers and I think many who use Prometheus + Grafana would find it very useful to see the statistics.
Personally, I need the following data:
* CPU and RAM load
* How many players are connected through the domain server1.exaple.com, server2.example.com, etc. and total connections
* If possible, display a list of these players (Nicknames)

**Comment by haveachin** [comment]
Official client library written in Go: https://github.com/prometheus/client_golang
Might need further investigation before implementation.

**Comment by lhridder** [comment]
#73
