### ISSUE TITLE
Not possible to accept direct ip connections

### ISSUE THREAD

**Issue by comendantmc** [haveachin/infrared#72]
When players are trying to connect to the ip instead of the domain name, they are getting disconnected with an error. It would be nice to be able to disable domain checking in the config

**Comment by haveachin** [comment]
This is by design. I will implement domain wildcards what will enable such functionality. See #37

**Comment by comendantmc** [comment]
I don't see how domain wildcards will allow to connect directly tp the ip address. Or can I just write the ip instead of the domain name in the config?

**Comment by haveachin** [comment]
`"domainName":"*"` will then allow everything as host name.
`"domainName":"123.4.567.89"` will probably result in similar results in your case.
BTW if you just want to proxy TCP traffic then I would suggest that you use something like HAProxy.

**Comment by comendantmc** [comment]
I actually switched from HAProxy to infrared today, because of TCPShield/RealIP Protocol Support.
Looking forward for domain wildcards then and thanks for your work
