### ISSUE TITLE
Add an option to disable shutting down docker containers

### ISSUE THREAD

**Issue by coolnickname** [haveachin/infrared#78]
**Is your feature request related to a problem? Please describe.**
I would like the proxy to start the server's docker container when it's offline and someone tries to connect but not turn it off when they disconnect.

**Describe the solution you'd like**
Add an option under the `docker` group along the type of `onlyStartup` that would disable shutting the server down by stopping the container, while maintaining the startup functionality.

**Describe alternatives you've considered**
None.

**Additional context**
This is would give us the option to stop the server with a plugin or mod which can take more conditions into consideration, like shutting down after no players have been online in 24 hours. This could also be a solution to the server shutting down while players with a direct connection are still online.

**Comment by haveachin** [comment]
Just do:
```json
{
    "docker": {
        "timeout": -1,
        ...
    },
    ...
}
```

**Comment by haveachin** [comment]
Oh, sorry. I just saw that the feature wasn't documented. Timeout is the time in seconds that Infrared waits until it stops the container.

**Comment by coolnickname** [comment]
Wow, thanks! That's an even better solution.
