### ISSUE TITLE
Restore player IPs from infraned

### ISSUE THREAD

**Issue by dada513** [haveachin/infrared#8]
I want to use this proxy, can it restore player IPs so IP bans work?

**Comment by dada513** [comment]
This would probably need a plugin, something like this: https://github.com/TCPShield/RealIP

**Comment by haveachin** [comment]
I see what your problem is and will address it soon

**Comment by MB175** [comment]
we already had a meeting according your issue , such functionality was already planed.
stay tuend such functionality's will arrive soon

**Comment by dada513** [comment]
any progress on this?

**Comment by dada513** [comment]
BungeeCord supports proxy-protocol. Maybe that could be used

**Comment by CM8DoubleCheck** [comment]
BungeeCord modifies the handshake packet which is 100% possible (I've done it with my own, private, proxy written in Go. You have to first parse the incoming handshake packet get the hostname of the connecting player, tack their IP on the end with some symbol between to split it later on, then reconstruct a new handshake packet from all of that to send to the server. The issue with using Spigot's BungeeCord support, however, is that it adds a lot of extra information onto the handshake packet as well, not just the player's IP. So, if you wanted that directly, you'd need the player's IP, UUID, and session token in order for Spigot to recognize it. These are not available to the proxy itself unless it's handling authentication (all servers behind it would have to be in offline mode. 

The real solution to this would be to forget about what Bungecord does and simply modify the hostname string in the handshake packet and then parse it on the backend server(s).

**Comment by MB175** [comment]
CM8DoubleCheck mentioned one Approach we are already working on, sadly we don't have time at all atm.

**Comment by CM8DoubleCheck** [comment]
@MB175 Feel free to add me on Discord, DoubleCheck#0001, if you're looking for some insight about the handshake packet. There are a few things that aren't well documented on wiki.vg that will cause some headaches.

**Comment by MB175** [comment]
@CM8DoubleCheck I will tell @haveachin to get in touch with you he breaths the Minecraft protocol atm and will be happy to know anything undiscovered

**Comment by haveachin** [comment]
@CM8DoubleCheck you don't accept friend requests on discord. Feel free to add me if you're more comfortable with that Haveachin#5170

**Comment by CM8DoubleCheck** [comment]
Submitted a pull request to add support for HAProxy's PROXY protocol which will forward IPs (#17).

BungeeCord supports the PROXY protocol by enabling `proxy_protocol`. I believe there are Bukkit & Spigot plugins to support it as well.

**Comment by dada513** [comment]
Thank you!!! Proxy protocol was all I needed.

**Comment by haveachin** [comment]
@dada513 can you confirm that it works for you?

**Comment by dada513** [comment]
Will do once I have time
