### ISSUE TITLE
Portainer in HTTPS mode not supported

### ISSUE THREAD

**Issue by coolnickname** [haveachin/infrared#80]
**Describe the bug**
Portainer configured to use HTTPS connections will drop all HTTP traffic. Infrared tries to connect over HTTP.

**To Reproduce**
Docker and Portainer configured in the server instance config. Portainer is configured to use SSL. Error:
`____:___ closed connection with :25565; error: Get "http://____.com:9000/api/endpoints/1/docker/v1.24/containers/json?all=1&limit=0": context deadline exceeded`

Trying this request URL with curl, or trying to visit Portainer over HTTP in general gives the following error:
`Client sent an HTTP request to an HTTPS server.`

**Expected behavior**
Automatically redirect to HTTPS when required.

I think the easiest solution would be to allow users to add http:// or https:// to the portainer adress config option, with it defaulting to http if not specified.

**Comment by haveachin** [comment]
Normally, the server should automatically upgrade the request. Are you using a reverse proxy?

**Comment by haveachin** [comment]
Reopen if needed
