### ISSUE TITLE
Dose anyone know how to port forward the infrared proxy without using a domain?

### ISSUE THREAD

**Issue by jameshackerbond** [haveachin/infrared#95]
Im trying to port forward my infrared proxy but dose it have it have an domain for players to connect?

**Comment by Mitch0S** [comment]
Hi James,

If you need a free domain (required for infrared to work) go to "freenom.com" here you can register a free domain name. Then you can look up a tutorial on using A records to forward a domain to a host, which would be the IP that is hosting infrared. If you need me to help you set this up, join the discord! 

Cheers,

Mitch, Ausguard.net

**Comment by haveachin** [comment]
Put you IP address in the domainName field. E.g.: `"domainName": "123.45.678.9"`

**Comment by jameshackerbond** [comment]
> Hi James,
> 
> If you need a free domain (required for infrared to work) go to "freenom.com" here you can register a free domain name. Then you can look up a tutorial on using A records to forward a domain to a host, which would be the IP that is hosting infrared. If you need me to help you set this up, join the discord!
> 
> Cheers,
> 
> Mitch, Ausguard.net

Hi there,

Can the record be like from the host domain A record like proxy.1b1e.org and then someone else uses a cname record pointing to that like Cname server.mchost.com -> proxy.1b1e.org?

**Comment by jameshackerbond** [comment]
> Put you IP address in the domainName field. E.g.: `"domainName": "123.45.678.9"`

dose it work with local ip's?

**Comment by haveachin** [comment]
Yes, it should work with everything that you can put in the minecraft server address field when connecting in the client.

**Comment by haveachin** [comment]
![image](https://user-images.githubusercontent.com/30272106/127000890-09259560-894f-41a6-aa9f-77f6d6c10065.png)
Infrared uses whatever a client puts in this field to connect the player to the right server in your backend. So in theory you could write anything in that box as long as it enough to connect to Infrared. This can be a FQDN or an IP address. It doesn't make a difference for the logic in Infrared.
