### ISSUE TITLE
Infrared not showing offline message when on tcpshield

### ISSUE THREAD

**Issue by jameshackerbond** [haveachin/infrared#97]
**Describe the bug**
Hi, I'm having some trouble with my infrared proxy. I have a it like this domain.??.org -> proxy.1b1e.org -> tcpshield.com -> infrared proxy (my end) -> server. But when I turn off the server it should show an offline message but  instead it shows
"Can't connect to server" at the MOTD and when trying to connect to the server it says "Disconnected."
**To Reproduce**
What OS are you using?
Windows_10_infrared_x86_64
{
  "domainName": "1b1e.org",
  "listenTo": ":25565",
  "proxyTo": "XD:25588",
  "proxyProtocol": false,
  "realIp": true,
  "timeout": 1000,
  "disconnectMessage": " §b{§3JamesShield§b} \n\n  §cSorry {{username}, {{domain}} is offline!  \n\n§3Please try again later.",
  "offlineStatus": {
    "versionName": "§b{§3JamesShield§b}",
    "protocolNumber": 1,
    "maxPlayers": 0,
    "playersOnline": 0,
    "motd": "§b{§3JamesShield§b} &cThis server is offline, Please try again later."
  }
}
I put the infrared proxy with tcpshield

**Expected behavior**
Show the offline motd and offline message when connecting

**Screenshots** (Optional)
![image](https://user-images.githubusercontent.com/82678869/127486692-230ea565-3ad2-4daa-ac7c-596b256f31c8.png)
![image](https://user-images.githubusercontent.com/82678869/127486716-2ce01a10-5456-4825-8886-dd5764bc8e53.png)

**Additional context** (Optional)
How do I fix this?

**Comment by jameshackerbond** [comment]
Is this an bug with tcpshield?

**Comment by haveachin** [comment]
Does it work when you connect directly to Infrared without TCPShield?

**Comment by jameshackerbond** [comment]
it dose work even connecting with tcpshield its about the offline message

**Comment by haveachin** [comment]
Is something happening in the minecraft server console when you try to connect?

**Comment by jameshackerbond** [comment]
Nothing shows up

**Comment by jameshackerbond** [comment]
> Is something happening in the minecraft server console when you try to connect?

no

**Comment by jameshackerbond** [comment]
I found an bypass
