### ISSUE TITLE
I need help with "iconPath"

### ISSUE THREAD

**Issue by Qjamesunderscore** [haveachin/infrared#99]
![image](https://user-images.githubusercontent.com/82678869/128770088-41c8009a-a283-4dd0-96ef-0a775ca6ed50.png)
![image](https://user-images.githubusercontent.com/82678869/128770147-75d94e6f-8359-46c5-8dd5-91d7e736939c.png)
![image](https://user-images.githubusercontent.com/82678869/128770255-567a6477-b902-463b-b1c6-65f4734059a2.png)

**Comment by lhridder** [comment]
Hi James, you should probably just put
`"configs\yourpicture.png"`
in the iconPath field, you are now specifying a folder and not a file.

**Comment by jameshackerbond** [comment]
> Hi James, you should probably just put
> `"configs\yourpicture.png"`
> in the iconPath field, you are now specifying a folder and not a file.

I tried that but its not working
gtg

**Comment by haveachin** [comment]
If your icons are in the icons folder then you should do something like this:
```json
"iconPath": "./icons/myicon.png",
```

**Comment by haveachin** [comment]
@jameshackerbond is this resolved?

**Comment by haveachin** [comment]
Reopen if needed
